-- require('lspconfig').vtsls.setup({
--   settings = {
--     complete_function_calls = true,
--     vtsls = {
--       enableMoveToFileCodeAction = true,
--       autoUseWorkspaceTsdk = true,
--     },
--     tsserver = {
--       globalPlugins = {
--         vue,
--       },
--     },
--     typescript = {
--       inlayHints = {
--         parameterNames = { enabled = 'literal' },
--         parameterTypes = { enabled = true },
--         variableTypes = { enabled = true },
--         propertyDeclarationTypes = { enabled = true },
--         functionLikeReturnTypes = { enabled = true },
--         enumMemberValues = { enabled = true },
--       },
--     },
--   },
-- })
