# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "dotnet-xunit";
    version = "2.3.1";
    hash = "sha256-pGghnfgZMfv6Fb49kLtdbtkcxvBuMsNhNhObFyfVP3A=";
  })
  (fetchNuGet {
    pname = "Libuv";
    version = "1.9.0";
    hash = "sha256-DjTLVqtEUVStzRjEMvhPeatqKs5OuuDhcHYSGGCi5ik=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "1.1.0";
    hash = "sha256-7KrZfK3kUbmeT82eVadvHurZcaFq3FDj4qkIIeExJiM=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "1.3.0";
    hash = "sha256-Jcw54WWyfPKdkeqRAG4xjihiGP/djjAkvpR6KM2I+CQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "1.3.0";
    hash = "sha256-OqqvMHNj9Xql4YTEPMlzoGXXELoLC7JkRGjS0pil+m4=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.VisualBasic";
    version = "1.3.0";
    hash = "sha256-lIKN1dG59aY8zeYgkY8Kdnv4UBgSwVbghz5ngPyEzKA=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "1.0.3";
    hash = "sha256-vO0DJv2QNYfus4VzqVkNcnWQqmuUrM5le7supZRl/Uk=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.0.1";
    hash = "sha256-0huoqR2CJ3Z9Q2peaKD09TV3E6saYSqDGZ290K8CrH8=";
  })
  (fetchNuGet {
    pname = "Microsoft.DotNet.PlatformAbstractions";
    version = "1.0.3";
    hash = "sha256-tE+2/zJAOpwaINSnmsq070K5xHQAzzqcrVkCxBFiXtk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "1.0.3";
    hash = "sha256-NEcjABwtUqoDs6mrYKHJZ8Rn0EN5krHitnxghez6lO0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "15.5.0";
    hash = "sha256-SFSwg74AaFv5IUBRAQOKExEuPU9CQFbP97Myi5SMevE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App";
    version = "1.0.0";
    hash = "sha256-V+YsHLTJKL4QE7kvSCQw5bCtmUAjkW6DTbbDo45mCUQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App";
    version = "2.0.0";
    hash = "sha256-op2W8RQ55eC+5TKYD1ZvuT0h6zSRqdxq7h5qlbWeHUk=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetAppHost";
    version = "2.0.0";
    hash = "sha256-jT+oiSZkd9S88BeH5ZY0uXdQHvTXNFBotn9RncNsPXo=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHost";
    version = "1.0.1";
    hash = "sha256-yiyZ4KGVRDZRgAuoSl4ZNWnRR3ityniyRPvzS799JOM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHostPolicy";
    version = "1.0.1";
    hash = "sha256-4dNpj9sxKfV1jEFDma2hM7d+xJ6+/wJwP3/SugLneG0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHostPolicy";
    version = "2.0.0";
    hash = "sha256-TnmtKfWidje2CVnwMb9Y0WcYroR3aHRoJFGxzb7z6f8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHostResolver";
    version = "1.0.1";
    hash = "sha256-hGJLA8Q6R+up9zHzk+Up2KF1a+fXZeEWrAZ+iNfQP4E=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHostResolver";
    version = "2.0.0";
    hash = "sha256-qw/aGePgrpt97N8iKreCL5hzc2Cnoge2yefjVnEvxHc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Jit";
    version = "1.0.2";
    hash = "sha256-T92T+bmdXfpAe73OKFTYXGJW1gTHuwcryBSgV7mwSkk=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.0.1";
    hash = "sha256-mZotlGZqtrqDSoBrZhsxFe6fuOv5/BIo0w2Z2x0zVAU=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    hash = "sha256-IEvBk6wUXSdyCnkj6tHahOJv290tVVT8tyemYcR0Yro=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Runtime.CoreCLR";
    version = "1.0.2";
    hash = "sha256-7K5EruLlrFmN3rAfXZMPK3hfhS728k5Gew0e+L3Ur8M=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.0.1";
    hash = "sha256-lxxw/Gy32xHi0fLgFWNj4YTFBSBkjx5l6ucmbTyf7V4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Windows.ApiSets";
    version = "1.0.1";
    hash = "sha256-6PR4o/wQxBaJ5eRdt/awSO80EP3QqpWIk0XkCR9kaJo=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies";
    version = "1.0.3";
    hash = "sha256-FBoJP5DHZF0QHM0xLm9yd4HJZVQOuSpSKA+VQRpphEE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net451";
    version = "1.0.3";
    hash = "sha256-dwsz36ZNxDDJ2bpOFDi5IN7pBffqYHkRR9cGifaGktM=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "15.5.0";
    hash = "sha256-bDhIkc3tfBeRBlg2tFprq/mSLy5blJ3Yy16lyDay2Rg=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "15.5.0";
    hash = "sha256-Qy97kvsDuXqrBH5KQJod44TxsJAZi8EaTQjNqu0MHV8=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualBasic";
    version = "10.0.1";
    hash = "sha256-7HHzZcWLVTTQ1K1rCIyoB+UxLHMvOIz+O5av6XDa22A=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.0.1";
    hash = "sha256-B4t5El/ViBdxALMcpZulewc4j/3SIXf71HhJWhm4Ctk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-mBNDmPXNTW54XLnPAUwBRvkIORFM7/j0D0I2SyQPDEg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "4.0.0";
    hash = "sha256-M/06F/Z2wTHCh4pZOgtCjUGLD1FJXEJKCmzOeFMl7uo=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.0";
    hash = "sha256-ExWI1EKDCRishcfAeHVS/RoJphqSqohmJIC/wz3ZtVo=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.1";
    hash = "sha256-iNan1ix7RtncGWC9AjAZ2sk70DoxOsmEOgQ10fXm4Pw=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.0";
    hash = "sha256-Pp7fRylai8JrE1O+9TGfIEJrAOmnWTJRLWE+qJBahK0=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "9.0.1";
    hash = "sha256-mYCBrgUhIJFzRuLLV9SIiIFHovzfR8Uuqfg6e08EnlU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-8yLKFt2wQxkEf7fNfzB+cPUCjYn2qbqNgQ1+EeY2h/I=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-dsmTLGvt8HqRkDWP8iKVXJCS+akAzENGXKPV18W2RgI=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-AYh39tgXJVFu8aLi9Y/4rK8yWMaza4S4eaxjfcuEEL4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-6MYj0RmLh4EVqMtO/MRqBi0HOn5iG4x9JimgCCJ+EFM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-BgHxXCIbicVZtpgMimSXixhFC3V+p5ODqeljDjO8hCs=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.Microsoft.NETCore.App";
    version = "2.0.0";
    hash = "sha256-twzpaOxUuJkREqhwC0PocLkpXyDcoPPTDaC90ckE4Yk=";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.Microsoft.NETCore.DotNetAppHost";
    version = "2.0.0";
    hash = "sha256-hXs5zBlHfNy9pW7WyKhHo9UN7HRFMtd+d3cMg/GAzYc=";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.Microsoft.NETCore.DotNetHostPolicy";
    version = "2.0.0";
    hash = "sha256-GWQcmZBgWcHMziYLdgxL7CS6SRPdeeSirPW51+w8rN8=";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.Microsoft.NETCore.DotNetHostResolver";
    version = "2.0.0";
    hash = "sha256-yOukfbFamSrrzwaRo4Yti1M0q8DcVisDUK3Guue6B+E=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.0.0";
    hash = "sha256-bmaM0ovT4X4aqDJOR255Yda/u3fmHZskU++lMnsy894=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Compression";
    version = "4.1.0";
    hash = "sha256-085JrZxNEwIHdBWKKKFsh1JzpF0AblvrUsz5T8kH4jQ=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-DWnXs4vlKoU6WxxvCArTJupV6sX3iBbZh8SbqfHace8=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.0.1";
    hash = "sha256-5nWnTQrA1T6t9r8MqIiV4yTNu+IH0of2OX1qteoS+8E=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.3.0";
    hash = "sha256-c556PyheRwpYhweBjSfIwEyZHnAUB8jWioyKEcp/2dg=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Security";
    version = "4.0.1";
    hash = "sha256-E64W+qCHZGYbhzQOEeToCob/4K8cTg3uOO7ltZG7ZNo=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography";
    version = "4.0.0";
    hash = "sha256-6Q8eYzC32BbGIiTHoQaE6B3cD81vYQcH5SCswYRSp0w=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-2IhBv0i6pTcOyr8FFIyfPEaaCHUmJZ8DYwLUwJ+5waw=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-serkd4A7F6eciPiPJtUyJyxzdAtupEcWIZQ9nptEzIM=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.unix.Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-LZb23lRXzr26tRS5aA0xyB08JxiblPDoA7HBvn6awXg=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Console";
    version = "4.3.0";
    hash = "sha256-AHkdKShTRHttqfMjmi+lPpTuCrM5vd/WRy6Kbtie190=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-Pf4mRl6YDK2x2KMh0WdyNgv0VUNdSKVDLlHqozecy5I=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-pHJ+I6i16MV6m77uhTC6GPY6jWGReE3SSP3fVB59ti0=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-IvgOeA2JuBjKl5yAVGjPYMPDzs9phb3KANs95H9v1w4=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.1.0";
    hash = "sha256-v6YfyfrKmhww+EYHUq6cwYUMj00MQ6SOfJtcGVRlYzs=";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.3.0";
    hash = "sha256-yg95LNQOwFlA1tWxXdQkVyJqT4AnoDc+ACmrNvzGiZg=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.0.0";
    hash = "sha256-+YUymoyS0O+xVyF2+LiAdZlMww8nofPN4ja9ylYqRo8=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.3.0";
    hash = "sha256-XqZWb4Kd04960h4U9seivjKseGA/YEIpdplfHYHQ9jk=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.0.11";
    hash = "sha256-puoFMkx4Z55C1XPxNw3np8nzNGjH+G24j43yTIsDRL0=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.0.12";
    hash = "sha256-zIEM7AB4SyE9u6G8+o+gCLLwkgi6+3rHQVPdn/dEwB8=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.3.0";
    hash = "sha256-KMY5DfJnDeIsa13DpqvyN8NkReZEMAFnlmNglVoFIXI=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.2.0";
    hash = "sha256-FQ3l+ulbLSPhQ0JcQCC4D4SzjTnHsRqcOj56Ywy7pMo=";
  })
  (fetchNuGet {
    pname = "System.Collections.NonGeneric";
    version = "4.0.1";
    hash = "sha256-jdCVXmGOsJ+2F0xAagCkiMZ91SGAm9iOhO2u4ksmKaU=";
  })
  (fetchNuGet {
    pname = "System.Collections.NonGeneric";
    version = "4.3.0";
    hash = "sha256-8/yZmD4jjvq7m68SPkJZLBQ79jOTOyT5lyzX4SCYAx8=";
  })
  (fetchNuGet {
    pname = "System.Collections.Specialized";
    version = "4.0.1";
    hash = "sha256-qao6hk9XKdRtpsqdks2uOx5jqT41KpuTCb1cg4w/e/E=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel";
    version = "4.0.1";
    hash = "sha256-X5T36S49q1odsn6wAET6EGNlsxOyd66naMr5T3G9mGw=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "4.1.0";
    hash = "sha256-jhvr6zS+iC4OXBkdXr+S8rPy/5nfhZtDVVJiAc0f1VA=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.EventBasedAsync";
    version = "4.0.11";
    hash = "sha256-kAOQ9dEg+yDh5h56qSf36OTLJYRIcKftIcOqxfuJJR8=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Primitives";
    version = "4.1.0";
    hash = "sha256-AIcFeZDeYbaI4V9lY8TtUG+xkUyhA8K8dYSDp5StZXE=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.TypeConverter";
    version = "4.1.0";
    hash = "sha256-HmzGTU2NVj8qUn1xCGxifOQ/e/HZCVvgIECzcJPaDJ0=";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.0.0";
    hash = "sha256-jtZfT/TpJtLisV/y5Mk3IfCpE79zwhBYXtyGP9jC3Xo=";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.3.0";
    hash = "sha256-Xh3PPBZr0pDbDaK8AEHbdGz7ePK6Yi1ZyRWI1JM6mbo=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.0.11";
    hash = "sha256-P+rSQJVoN6M56jQbs76kZ9G3mAWFdtF27P/RijN8sj4=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.0.0";
    hash = "sha256-dYh9UoFesuGcHY+ewsI+z2WnNy+bwHPsHQ3t85cbzNg=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.3.0";
    hash = "sha256-OFJRb0ygep0Z3yDBLwAgM/Tkfs4JCDtsNhwDH9cd1Xw=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.FileVersionInfo";
    version = "4.0.0";
    hash = "sha256-Yy94jPhDXF2QHOF7qTmqKkn1048K9xkKryuBeDzsu+g=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Process";
    version = "4.1.0";
    hash = "sha256-OgW6ogQ+oYADYS0PHmwXdhrOKQJpqXlwzSvmfjTLNBg=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.StackTrace";
    version = "4.0.1";
    hash = "sha256-gqqCAwpDsca242nli+fejgqwPAuwROv3NoNeOnFXSWA=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.TextWriterTraceListener";
    version = "4.0.0";
    hash = "sha256-GmInHGlq5ZTnT7qsxpKnXid11hcRXVBhA1N1zyePL/Y=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.0.1";
    hash = "sha256-vSBqTbmWXylvRa37aWyktym+gOpsvH43mwr6A962k6U=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-gVOv1SK6Ape0FQhCVlNOd9cvQKBvMxRX9K0JPVi8w0Y=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.TraceSource";
    version = "4.0.0";
    hash = "sha256-cCjdPU7ow91HGf1hBIOLJMQGO6pNmF+N+5/Z38XJh9U=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.1.0";
    hash = "sha256-JA0jJcLbU3zh52ub3zweob2EVHvxOqiC6SCYHrY5WbQ=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-hCETZpHHGVhPYvb4C0fh4zs+8zv4GPoixagkLZjpa9Q=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.0.11";
    hash = "sha256-qWqFVxuXioesVftv2RVJZOnmojUvRjb7cS3Oh3oTit4=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.0.11";
    hash = "sha256-rbSgc2PIEc2c2rN6LK3qCREAX3DqA2Nq1WcLrZYsDBw=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.0.1";
    hash = "sha256-EJN3LbN+b0O9Dr2eg7kfThCYpne0iJ/H/GIyUTNVYC8=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-uNOD0EOVFgnS2fMKvMiEtI9aOw00+Pfy/H+qucAQlPc=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.0.1";
    hash = "sha256-zLtkPryJwqTGcJqMC6zoMMvMrT+aAL5GoumjmMtqUEI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.3.0";
    hash = "sha256-mmJWA27T0GRVuFP9/sj+4TrR4GJWrzNIk2PDrbr7RQk=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.1.0";
    hash = "sha256-V6oyQFwWb8NvGxAwvzWnhPxy9dKOfj/XBM3tEC5aHrw=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.1.0";
    hash = "sha256-UT4KEfJNZOk7b4X0AqLFUsqfHu6myVH/BhbRKYc+1Uc=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-f5PrQlQgj5Xj2ZnHxXW8XiOivaBvfqDao9Sb6AVinyA=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.0.1";
    hash = "sha256-An0Twb9JODl/nuVm6MR0kJ3aj4WxGpI/1/vVp5b94kA=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.3.0";
    hash = "sha256-WQl+JgWs+GaRMeiahTFUbrhlXIHapzcpTFXbRvAtvvs=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.0.1";
    hash = "sha256-4VKXFgcGYCTWVXjAlniAVq0dO3o5s8KHylg2wg2/7k0=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-vNIYnvlayuVj0WfRfYKpDrhDptlhp1pN8CYmlVd2TXw=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.0.1";
    hash = "sha256-IpigKMomqb6pmYWkrlf0ZdpILtRluX2cX5sOKVW0Feg=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    hash = "sha256-LMnfg8Vwavs9cMnq9nNH8IWtAtSfk0/Fy4s4Rt9r1kg=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Watcher";
    version = "4.0.0";
    hash = "sha256-OcLhbiHvn453sJsZBHe6RmtDlCaaarcqRB439HGU7mU=";
  })
  (fetchNuGet {
    pname = "System.IO.MemoryMappedFiles";
    version = "4.0.0";
    hash = "sha256-1VQa8FoMUNAsja31OvOn7ungif+IPusAe9YcR+kRF6o=";
  })
  (fetchNuGet {
    pname = "System.IO.UnmanagedMemoryStream";
    version = "4.0.1";
    hash = "sha256-Sx60QjHjvXQMAL7O4aN81321gu13LE0XzCRtt7hFTwQ=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.1.0";
    hash = "sha256-ZQpFtYw5N1F1aX0jUK3Tw+XvM5tnlnshkTCNtfVA794=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.1.0";
    hash = "sha256-7zqB+FXgkvhtlBzpcZyd81xczWP0D3uWssyAGw3t7b4=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    hash = "sha256-+3pvhZY7rip8HCbfdULzjlC9FPZFpYoQxhkcuFm2wk8=";
  })
  (fetchNuGet {
    pname = "System.Linq.Parallel";
    version = "4.0.1";
    hash = "sha256-TV1F3KYFipPmPnWFjX6hOZQNFsG2m729EdgPSFzqY0Q=";
  })
  (fetchNuGet {
    pname = "System.Linq.Queryable";
    version = "4.0.1";
    hash = "sha256-XOFRO+lyoxsWtIUJfg5JCqv9Gx35ASOc94WIR8ZMVoY=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.1.0";
    hash = "sha256-y6PnGuObJvOkhl9CXNFJQcV3SXuEz5yRLOCxGGTEucQ=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.0";
    hash = "sha256-UoBB7WPDp2Bne/fwxKF0nE8grJ6FzTMXdT/jfsphj8Q=";
  })
  (fetchNuGet {
    pname = "System.Net.NameResolution";
    version = "4.0.0";
    hash = "sha256-EAO67qEDqrtxEa+J3xccA5/lgCJ0PiRU9DYZsO++QzY=";
  })
  (fetchNuGet {
    pname = "System.Net.NameResolution";
    version = "4.3.0";
    hash = "sha256-eGZwCBExWsnirWBHyp2sSSSXp6g7I6v53qNmwPgtJ5c=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.0.11";
    hash = "sha256-2YSijNhCdw/ZU2yfH7vE+ReA8pgxRCXPnWr+ab36v4M=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-MY7Z6vOtFMbEKaLW9nOSZeAjcWpwCtdO7/W1mkGZBzE=";
  })
  (fetchNuGet {
    pname = "System.Net.Requests";
    version = "4.0.11";
    hash = "sha256-MLXxaUhHQC3pId/6r4q0EF37CIExt0+4Na8ZpUtRs44=";
  })
  (fetchNuGet {
    pname = "System.Net.Security";
    version = "4.0.0";
    hash = "sha256-65Vqr/B5B336KEW69aM95+f7s5u2Q7/OiJmBarV2fnk=";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.1.0";
    hash = "sha256-muK7oXIX7ykqhXskuUt0KX6Hzg5VogJhUS0JiOB2BY0=";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-il7dr5VT/QWDg/0cuh+4Es2u8LY//+qqiY9BZmYxSus=";
  })
  (fetchNuGet {
    pname = "System.Net.WebHeaderCollection";
    version = "4.0.1";
    hash = "sha256-uJSV6kmL+V/9/ot1LhHXGCd8Ndcu6zk+AJ8wgGS/fYE=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.1.1";
    hash = "sha256-Kv4FrStml5+X7hGDCLhJJaIwJDvdJdYMBfcCcOjNf/Y=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.0.12";
    hash = "sha256-MudZ/KYcvYsn2cST3EE049mLikrNkmE7QoUoYKKby+s=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    hash = "sha256-gtmRkWP2Kwr3nHtDh0yYtce38z1wrGzb6fjm4v8wN6Q=";
  })
  (fetchNuGet {
    pname = "System.Private.DataContractSerialization";
    version = "4.1.1";
    hash = "sha256-OaE+ZcEfkpIkbdMOMAMiJa9vgiVP25FGuFrf+N/mafY=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.1.0";
    hash = "sha256-idZHGH2Yl/hha1CM4VzLhsaR8Ljo/rV7TYe7mwRJSMs=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.DispatchProxy";
    version = "4.0.1";
    hash = "sha256-GdjA81UywW1yeAyNi+MR5agmOXl859GrWwiOui2jT9U=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.0.1";
    hash = "sha256-F1MvYoQWHCY89/O4JBwswogitqVvKuVfILFqA7dmuHk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    hash = "sha256-5LhkDmhy2FkSxulXR+bsTtMzdU3VyyuZzsxp7/DwyIU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.0.1";
    hash = "sha256-YG+eJBG5P+5adsHiw/lhJwvREnvdHw6CJyS8ZV4Ujd0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    hash = "sha256-mKRknEHNls4gkRwrEgi39B+vSaAz/Gt3IALtS98xNnA=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.0.1";
    hash = "sha256-uVvNOnL64CPqsgZP2OLqNmxdkZl6Q0fTmKmv9gcBi+g=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    hash = "sha256-rKx4a9yZKcajloSZHr4CKTVJ6Vjh95ni+zszPxWjh2I=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.0.1";
    hash = "sha256-NsfmzM9G/sN3H8X2cdnheTGRsh7zbRzvegnjDzDH/FQ=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.3.0";
    hash = "sha256-a/RQr++mSsziWaOTknicfIQX/zJrwPFExfhK6PM0tfg=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.0.1";
    hash = "sha256-SFSfpWEyCBMAOerrMCOiKnpT+UAWTvRcmoRquJR6Vq0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.1.0";
    hash = "sha256-R0YZowmFda+xzKNR4kKg7neFoE30KfZwp/IwfRSKVK4=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.3.0";
    hash = "sha256-4U4/XNQAnddgQIHIJq3P2T80hN0oPdU2uCeghsDTWng=";
  })
  (fetchNuGet {
    pname = "System.Resources.Reader";
    version = "4.0.0";
    hash = "sha256-NOax26EYc/L4bfedL2a33fg4sFXVkBwzVTQ41saJTsk=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.0.1";
    hash = "sha256-cZ2/3/fczLjEpn6j3xkgQV9ouOVjy4Kisgw5xWw9kSw=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.1.0";
    hash = "sha256-FViNGM/4oWtlP6w0JC0vJU+k9efLKZ+yaXrnEeabDQo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.1.0";
    hash = "sha256-X7DZ5CbPY7jHs20YZ7bmcXs9B5Mxptu/HnBUvUnNhGc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.0.1";
    hash = "sha256-j2QgVO9ZOjv7D1het98CoFpjoYgxjupuIhuBUmLLH7w=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.1.0";
    hash = "sha256-QceAYlJvkPRJc/+5jR+wQpNNI3aqGySWWSO30e/FfQY=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.0.0";
    hash = "sha256-5j53amb76A3SPiE3B0llT2XPx058+CgE7OXL4bLalT4=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.3.0";
    hash = "sha256-MYpl6/ZyC6hjmzWRIe+iDoldOMW1mfbwXsduAnXIKGA=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Loader";
    version = "4.0.0";
    hash = "sha256-gE5/ehU3Qq5phhSxGuPmSv1DFVQeiyl1/+YyrO+I7lI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.0.1";
    hash = "sha256-1pJt5ZGxLPTX1mjOi8qZPXyyOMkYV0NstoUCv91HYPg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.3.0";
    hash = "sha256-P5jHCgMbgFMYiONvzmaKFeOqcAIDPu/U8bOVrNPYKqc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Serialization.Json";
    version = "4.0.2";
    hash = "sha256-thmzgYbyxoPYtkDdDwoG7wnVuVhFNwLUE2AsDfRf1yM=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Serialization.Primitives";
    version = "4.1.1";
    hash = "sha256-80B05oxJbPLGq2pGOSl6NlZvintX9A1CNpna2aN0WRA=";
  })
  (fetchNuGet {
    pname = "System.Security.Claims";
    version = "4.0.1";
    hash = "sha256-xqI0HHahNAd9g3jqgnLKH4P/pIueef6cy3qvRDQFvA0=";
  })
  (fetchNuGet {
    pname = "System.Security.Claims";
    version = "4.3.0";
    hash = "sha256-Fua/rDwAqq4UByRVomAxMPmDBGd5eImRqHVQIeSxbks=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.2.0";
    hash = "sha256-BelNIpEyToEp/VYKnje/q1P7KNEpQNtOzGPU18pLGpE=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.3.0";
    hash = "sha256-tAJvNSlczYBJ3Ed24Ae27a55tq/n4D3fubNQdwcKWA8=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.2.0";
    hash = "sha256-7F+m3HnmBsgE4xWF8FeCGlaEgQM3drqA6HEaQr6MEoU=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.3.0";
    hash = "sha256-u17vy6wNhqok91SrVLno2M1EzLHZm6VMca85xbVChsw=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.0.0";
    hash = "sha256-WHyR6vVK3zaT4De7jgQFUar1P5fiX9ECwiVkJDFFm7M=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.3.0";
    hash = "sha256-oefdTU/Z2PWU9nlat8uiRDGq/PGZoSPRgkML11pmvPQ=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.0.0";
    hash = "sha256-ZO7ha39J5uHkIF2RoEKv/bW/bLbVvYMO4+rWyYsKHik=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.3.0";
    hash = "sha256-Yuge89N6M+NcblcvXMeyHZ6kZDfwBv3LPMDiF8HhJss=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.0.0";
    hash = "sha256-mLijAozynzjiOMyh2P5BHcfVq3Ovd0T/phG08SIbXZs=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-DL+D2sc2JrQiB4oAcUggTFyD8w3aLEjJfod5JPe+Oz4=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.0.0";
    hash = "sha256-sEdPftfTxQd/8DpdpqUZC2XWC0SjVCPqAkEleLl17EQ=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.3.0";
    hash = "sha256-fnFi7B3SnVj5a+BbgXnbjnGNvWrCEU6Hp/wjsjWz318=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.1.0";
    hash = "sha256-sBUUhJP+yYDXvcjNMKqNpn8yzGUpVABwK9vVUvYKjzI=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.3.0";
    hash = "sha256-MG3V/owDh273GCUPsGGraNwaVpcydupl3EtPXj6TVG0=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.0.1";
    hash = "sha256-9wBgPnJfFOtrhKZ7wDXZ4q12GklQ49Ka02/9v7Frf9k=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.3.0";
    hash = "sha256-rjudVUHdo8pNJg2EVEn0XxxwNo5h2EaYo+QboPkXlYk=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.0.0";
    hash = "sha256-38wEUCB889Mpm4WgRFEQBB+4HtE0X0wu+knrDyJie7Q=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.3.0";
    hash = "sha256-mbdLVUcEwe78p3ZnB6jYsizNEqxMaCAWI3tEQNhRQAE=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.0.11";
    hash = "sha256-PEailOvG05CVgPTyKLtpAgRydlSHmtd5K0Y8GSHY2Lc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.0.1";
    hash = "sha256-wxtwWQSTv5tuFP79KhUAhaL6bL4d8lSzSWkCn9aolwM=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.0.11";
    hash = "sha256-+kf7J3dEhgCbnCM5vHYlsTm5/R/Ud0Jr6elpHm922iI=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-vufHXg8QAKxHlujPHHcrtGwAqFmsCD6HKjfDAiHyAYc=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.1.0";
    hash = "sha256-x6OQN6MCN7S0fJ6EFTfv4rczdUWjwuWE9QQ0P6fbh9c=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.3.0";
    hash = "sha256-VLCk1D1kcN2wbAe3d0YQM/PqCsPHOuqlBY1yd2Yo+K0=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.0.11";
    hash = "sha256-mob1Zv3qLQhQ1/xOLXZmYqpniNUMCfn02n8ZkaAhqac=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Overlapped";
    version = "4.0.1";
    hash = "sha256-CAWZlavcuBQHs+kaSX9CmkpHF7wC8rFrug3XPb5KJzo=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.0.11";
    hash = "sha256-5SLxzFg1df6bTm2t09xeI01wa5qQglqUwwJNlQPJIVs=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "4.6.0";
    hash = "sha256-YYrT3GRzVBdendxt8FUDCnOBJi0nw/CJ9VrzcPJWLSg=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.0.0";
    hash = "sha256-+YdcPkMhZhRbMZHnfsDwpNbUkr31X7pQFGxXYcAPZbE=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.3.0";
    hash = "sha256-X2hQ5j+fxcmnm88Le/kSavjiGOmkcumBGTZKBLvorPc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Parallel";
    version = "4.0.1";
    hash = "sha256-5VyRZ97Fug4reK/cQ6wsCrJ5jH53aGu1a4ZkKMZrnIQ=";
  })
  (fetchNuGet {
    pname = "System.Threading.Thread";
    version = "4.0.0";
    hash = "sha256-7EtSJuKqcW107FYA5Ko9NFXEWUPIzNDtlfKaQV2pvb8=";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.0.10";
    hash = "sha256-/fowWjM/0ZZFC1Rwu0i5N71iRxV2JOd3jQV2Jn0wuTk=";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.3.0";
    hash = "sha256-wW0QdvssRoaOfQLazTGSnwYTurE4R8FxDx70pYkL+gg=";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.0.1";
    hash = "sha256-5lU6zt1O9JDSPr2KAHw4BYgysHnt0yyZrMNa5IIjxZY=";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-pmhslmhQhP32TWbBzoITLZ4BoORBqYk25OWbru04p9s=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.0.11";
    hash = "sha256-haZAFFQ9Sl2DhfvEbdx2YRqKEoxNMU5STaqpMmXw0zA=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.3.0";
    hash = "sha256-QQ8KgU0lu4F5Unh+TbechO//zaAGZ4MfgvW72Cn1hzA=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.0.11";
    hash = "sha256-KPz1kxe0RUBM+aoktJ/f9p51GudMERU8Pmwm//HdlFg=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.3.0";
    hash = "sha256-rWtdcmcuElNOSzCehflyKwHkDRpiOhJJs8CeQ0l1CCI=";
  })
  (fetchNuGet {
    pname = "System.Xml.XmlDocument";
    version = "4.0.1";
    hash = "sha256-gdoFrPo54v1LjkBF79f8EvtltVVjHz9ZI9kc5ve0GkY=";
  })
  (fetchNuGet {
    pname = "System.Xml.XmlDocument";
    version = "4.3.0";
    hash = "sha256-kbuV4Y7rVJkfMp2Kgoi8Zvdatm9CZNmlKB3GZgANvy4=";
  })
  (fetchNuGet {
    pname = "System.Xml.XmlSerializer";
    version = "4.0.11";
    hash = "sha256-v6x4d6W18dijG5cDqQmVHdtWRf6Y4OkdBolT3d5g3wY=";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath";
    version = "4.0.1";
    hash = "sha256-lQCoK2M51SGRuGjfiuIW26Y2goABY2RLE6cZ4816WDo=";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath";
    version = "4.3.0";
    hash = "sha256-kd1JMqj6obhxzEPRJeYvcUyJqkOs/9A0UOQccC6oYrM=";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath.XDocument";
    version = "4.0.1";
    hash = "sha256-H/zyMMB1YB8vd+StYJr99KLqWmSHhaP7RHDLRcFhzbo=";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath.XDocument";
    version = "4.3.0";
    hash = "sha256-dqk4CWuwocj5qsUAYlS+XAe6GGcY/N/HIPEGe5afrPM=";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath.XmlDocument";
    version = "4.0.1";
    hash = "sha256-bK9AfAYrdSipdRbmo8Rk7394ku92UFNe2TEQF5+k/lA=";
  })
  (fetchNuGet {
    pname = "xunit";
    version = "2.3.1";
    hash = "sha256-PA6mgsNcAfsYtPttJMwP2vvJFkEHr1TWBbinHHy2cZU=";
  })
  (fetchNuGet {
    pname = "xunit.abstractions";
    version = "2.0.1";
    hash = "sha256-v5iPVeoUFsZp9zQMt3rg6xgw6UwF4VMIgzVYFIeb/zA=";
  })
  (fetchNuGet {
    pname = "xunit.analyzers";
    version = "0.7.0";
    hash = "sha256-pBSXejaitnWyjj2tMuXrRW+Pnhc+tY176rB0lj9pGSw=";
  })
  (fetchNuGet {
    pname = "xunit.assert";
    version = "2.3.1";
    hash = "sha256-nsBTofz/qJ3a2FxABojZoz7Iosz7I6bDf+OcOzre3c8=";
  })
  (fetchNuGet {
    pname = "xunit.core";
    version = "2.3.1";
    hash = "sha256-49p0DfPlJv6fs5t5XyjHZVu4za5nBipw6s0uTvfnHDk=";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.core";
    version = "2.3.1";
    hash = "sha256-iszk3oNIIE62vp2OpYMPB9FhMP44YpPInMXqeyXtl4o=";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.execution";
    version = "2.3.1";
    hash = "sha256-IBOOtb5/LdtXVG/R0Q4GyKPt/v2+q3OBIldi+y42tGg=";
  })
  (fetchNuGet {
    pname = "xunit.runner.visualstudio";
    version = "2.3.1";
    hash = "sha256-JKLVlVa8jjrdI2HmOy/BcoUG9N6FXmWZKQYkzx+ggDE=";
  })
  (fetchNuGet {
    pname = "YamlDotNet";
    version = "5.0.0";
    hash = "sha256-TXL5Ls7K9FrjJIjDRpahm/Ey24bPsPkIbIy6NMsRQLs=";
  })
]
