Alt+. playlist-next
Alt+, playlist-prev

l frame-step # advance one frame and pause
h frame-back-step

Alt+Enter cycle fullscreen

g-g playlist-play-index 0
G set playlist-pos-1 ${playlist-count}

r cycle_values video-rotate "90" "180" "270" "0"
alt+v vf toggle flip # vertical mirror
alt+h vf toggle hflip # horizontal mirror

m ab-loop
s cycle mute

w screenshot
W screenshot video # ss without subtitle

ctrl+l cycle-values loop-file "inf" "no"
ctrl+shift+l cycle-values loop-playlist yes no

ctrl+= add volume 2
ctrl+- add volume -2

alt+= add video-zoom 0.1
alt+- add video-zoom -0.1
