# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Humanizer.Core";
    version = "2.14.1";
    hash = "sha256-EXvojddPu+9JKgOG9NSQgUTfWq1RpOYw7adxDPKDJ6o=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/humanizer.core/2.14.1/humanizer.core.2.14.1.nupkg";
  })
  (fetchNuGet {
    pname = "Json.More.Net";
    version = "2.0.1.2";
    hash = "sha256-fnp/By8n8xKa8bhvUbO2p8rlze5AvgA+z9ZvWEpL/Ls=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/json.more.net/2.0.1.2/json.more.net.2.0.1.2.nupkg";
  })
  (fetchNuGet {
    pname = "JsonPointer.Net";
    version = "5.0.0";
    hash = "sha256-OCeXHpJyHJSyh2vpnrY8nSuM4u3eNXtN6YXnJZyHnWc=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/jsonpointer.net/5.0.0/jsonpointer.net.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "JsonSchema.Net";
    version = "7.0.4";
    hash = "sha256-sCaGr8m20DzNEkF3TS7Cb+wmvo3hYZPZwQ2bTqwlB5g=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/jsonschema.net/7.0.4/jsonschema.net.7.0.4.nupkg";
  })
  (fetchNuGet {
    pname = "Markdig.Signed";
    version = "0.33.0";
    hash = "sha256-0ARhEK5hlzkvF07tTO34znZwcYMFQjob5D2rDWylJiA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/markdig.signed/0.33.0/markdig.signed.0.33.0.nupkg";
  })
  (fetchNuGet {
    pname = "MediatR";
    version = "8.1.0";
    hash = "sha256-dyqhDG1NJjY1b+dj37sMmklGkxAm3zKdhh2lBJ0/HTM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/mediatr/8.1.0/mediatr.8.1.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.ApplicationInsights";
    version = "2.21.0";
    hash = "sha256-nTDLtTz7HwG8urKKt4aztnpwObgygjZbo2j1iZckA+A=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.applicationinsights/2.21.0/microsoft.applicationinsights.2.21.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    hash = "sha256-49+H/iFwp+AfCICvWcqo9us4CzxApPKC37Q5Eqrw+JU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.bcl.asyncinterfaces/6.0.0/microsoft.bcl.asyncinterfaces.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "7.0.0";
    hash = "sha256-1e031E26iraIqun84ad0fCIR4MJZ1hcQo4yFN+B7UfE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.bcl.asyncinterfaces/7.0.0/microsoft.bcl.asyncinterfaces.7.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "8.0.0";
    hash = "sha256-9aWmiwMJKrKr9ohD1KSuol37y+jdDxPGJct3m2/Bknw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.bcl.asyncinterfaces/8.0.0/microsoft.bcl.asyncinterfaces.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "9.0.0";
    hash = "sha256-BsXNOWEgfFq3Yz7VTtK6m/ov4/erRqyBzieWSIpmc1U=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.bcl.asyncinterfaces/9.0.0/microsoft.bcl.asyncinterfaces.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.4";
    hash = "sha256-qDzTfZBSCvAUu9gzq2k+LOvh6/eRvJ9++VCNck/ZpnE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.codeanalysis.analyzers/3.3.4/microsoft.codeanalysis.analyzers.3.3.4.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.9.2";
    hash = "sha256-QU/nyiJWpdPQGHBdaOEVc+AghnGHcKBFBX0oyhRZ9CQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.codeanalysis.common/4.9.2/microsoft.codeanalysis.common.4.9.2.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.9.2";
    hash = "sha256-j06Q4A9E65075SBXdXVCMRgeLxA63Rv1vxarydmmVAA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.codeanalysis.csharp/4.9.2/microsoft.codeanalysis.csharp.4.9.2.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.10.0";
    hash = "sha256-yQFwqVChRtIRpbtkJr92JH2i+O7xn91NGbYgnKs8G2g=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.codecoverage/17.10.0/microsoft.codecoverage.17.10.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    hash = "sha256-Enknv2RsFF68lEPdrf5M+BpV1kHoLTVRApKUwuk/pj0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.csharp/4.7.0/microsoft.csharp.4.7.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "6.0.1";
    hash = "sha256-v55PAURxnSGYgbv9x+4/pMeI51H27ikRfHBuUB+N5nE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.configuration/6.0.1/microsoft.extensions.configuration.6.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "6.0.0";
    hash = "sha256-Evg+Ynj2QUa6Gz+zqF+bUyfGD0HI5A2fHmxZEXbn3HA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.configuration.abstractions/6.0.0/microsoft.extensions.configuration.abstractions.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "6.0.0";
    hash = "sha256-7NZcKkiXWSuhhVcA/fXHPY/62aGUyMsRdiHm91cWC5Y=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.configuration.binder/6.0.0/microsoft.extensions.configuration.binder.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "6.0.1";
    hash = "sha256-V+CulDoU3NXWn5EjH64JhDVQ0h+ev5BW95T+2uL1hU4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.dependencyinjection/6.0.1/microsoft.extensions.dependencyinjection.6.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "9.0.0";
    hash = "sha256-dAH52PPlTLn7X+1aI/7npdrDzMEFPMXRv4isV1a+14k=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.dependencyinjection/9.0.0/microsoft.extensions.dependencyinjection.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "6.0.0";
    hash = "sha256-SZke0jNKIqJvvukdta+MgIlGsrP2EdPkkS8lfLg7Ju4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.dependencyinjection.abstractions/6.0.0/microsoft.extensions.dependencyinjection.abstractions.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "9.0.0";
    hash = "sha256-CncVwkKZ5CsIG2O0+OM9qXuYXh3p6UGyueTHSLDVL+c=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.dependencyinjection.abstractions/9.0.0/microsoft.extensions.dependencyinjection.abstractions.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileSystemGlobbing";
    version = "8.0.0";
    hash = "sha256-+Oz41JR5jdcJlCJOSpQIL5OMBNi+1Hl2d0JUHfES7sU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.filesystemglobbing/8.0.0/microsoft.extensions.filesystemglobbing.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "6.0.0";
    hash = "sha256-8WsZKRGfXW5MsXkMmNVf6slrkw+cR005czkOP2KUqTk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.logging/6.0.0/microsoft.extensions.logging.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "9.0.0";
    hash = "sha256-kR16c+N8nQrWeYLajqnXPg7RiXjZMSFLnKLEs4VfjcM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.logging/9.0.0/microsoft.extensions.logging.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.0";
    hash = "sha256-QNqcQ3x+MOK7lXbWkCzSOWa/2QyYNbdM/OEEbWN15Sw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.logging.abstractions/6.0.0/microsoft.extensions.logging.abstractions.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "9.0.0";
    hash = "sha256-iBTs9twjWXFeERt4CErkIIcoJZU1jrd1RWCI8V5j7KU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.logging.abstractions/9.0.0/microsoft.extensions.logging.abstractions.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Debug";
    version = "9.0.0";
    hash = "sha256-5W6fP9Eb98U3MTWKeLzSNl2cRFpE694OOPjpWp/qTAk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.logging.debug/9.0.0/microsoft.extensions.logging.debug.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "8.0.10";
    hash = "sha256-uFDHjHlJ/FqSjBMlEZbSGX46M/ijrKEoKTcAEaRqaog=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.objectpool/8.0.10/microsoft.extensions.objectpool.8.0.10.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "6.0.0";
    hash = "sha256-DxnEgGiCXpkrxFkxXtOXqwaiAtoIjA8VSSWCcsW0FwE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.options/6.0.0/microsoft.extensions.options.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "9.0.0";
    hash = "sha256-DT5euAQY/ItB5LPI8WIp6Dnd0lSvBRP35vFkOXC68ck=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.options/9.0.0/microsoft.extensions.options.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "6.0.0";
    hash = "sha256-au0Y13cGk/dQFKuvSA5NnP/++bErTk0oOTlgmHdI2Mw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.options.configurationextensions/6.0.0/microsoft.extensions.options.configurationextensions.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "6.0.0";
    hash = "sha256-AgvysszpQ11AiTBJFkvSy8JnwIWTj15Pfek7T7ThUc4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.primitives/6.0.0/microsoft.extensions.primitives.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "9.0.0";
    hash = "sha256-ZNLusK1CRuq5BZYZMDqaz04PIKScE2Z7sS2tehU7EJs=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.extensions.primitives/9.0.0/microsoft.extensions.primitives.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Management.Infrastructure";
    version = "3.0.0";
    hash = "sha256-vVpri69Zhd5h8B7wP9skDsgX5V7TsKI39yLXjWXqsnI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.management.infrastructure/3.0.0/microsoft.management.infrastructure.3.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Management.Infrastructure.CimCmdlets";
    version = "7.4.6";
    hash = "sha256-QmFBHebf3d8b9ZruKlhh1EKdRBfsqqnRHA3VN1SqLJA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.management.infrastructure.cimcmdlets/7.4.6/microsoft.management.infrastructure.cimcmdlets.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Management.Infrastructure.Runtime.Unix";
    version = "3.0.0";
    hash = "sha256-tPlZutCN+abmgMMyAPXO/nwbgiKibrE00zjeC1ZUJas=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.management.infrastructure.runtime.unix/3.0.0/microsoft.management.infrastructure.runtime.unix.3.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Management.Infrastructure.Runtime.Win";
    version = "3.0.0";
    hash = "sha256-cgbo8wyCQGb7NKl3lbqI5HM6aVjp4I+6dG4DXvYHXzQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.management.infrastructure.runtime.win/3.0.0/microsoft.management.infrastructure.runtime.win.3.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.10.0";
    hash = "sha256-rkHIqB2mquNXF89XBTFpUL2z5msjTBsOcyjSBCh36I0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.net.test.sdk/17.10.0/microsoft.net.test.sdk.17.10.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.netcore.platforms/1.1.0/microsoft.netcore.platforms.1.1.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "3.1.0";
    hash = "sha256-cnygditsEaU86bnYtIthNMymAHqaT/sf9Gjykhzqgb0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.netcore.platforms/3.1.0/microsoft.netcore.platforms.3.1.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    hash = "sha256-LIcg1StDcQLPOABp4JRXIs837d7z0ia6+++3SF3jl1c=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.netcore.platforms/5.0.0/microsoft.netcore.platforms.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.netcore.targets/1.1.0/microsoft.netcore.targets.1.1.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies";
    version = "1.0.3";
    hash = "sha256-FBoJP5DHZF0QHM0xLm9yd4HJZVQOuSpSKA+VQRpphEE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.netframework.referenceassemblies/1.0.3/microsoft.netframework.referenceassemblies.1.0.3.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net462";
    version = "1.0.3";
    hash = "sha256-7mkqhFdDUAkQhV1MMwym6e+HwW4W90DkR00YcYXWbiE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.netframework.referenceassemblies.net462/1.0.3/microsoft.netframework.referenceassemblies.net462.1.0.3.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.5.ReferenceAssemblies";
    version = "1.1.0";
    hash = "sha256-K8WrRfIL+l2dFBYRz4towjqNlDcfAbzqZeX3Gobe6kU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.5.referenceassemblies/1.1.0/microsoft.powershell.5.referenceassemblies.1.1.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.Commands.Diagnostics";
    version = "7.4.6";
    hash = "sha256-YFIy+ui7lh6BbkdUt0mSHfQcYgK2uFf0NwGqdu/uiKY=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.commands.diagnostics/7.4.6/microsoft.powershell.commands.diagnostics.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.Commands.Management";
    version = "7.4.6";
    hash = "sha256-2dzEOc3Nsa7VbmV2EaOzUcn3Weu/8tPxfjz1KWDLHPM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.commands.management/7.4.6/microsoft.powershell.commands.management.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.Commands.Utility";
    version = "7.4.6";
    hash = "sha256-S9H5FW3VP0ixFfe+fIDZZER9U3bgAC7nNQSYsVA5Xxg=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.commands.utility/7.4.6/microsoft.powershell.commands.utility.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.ConsoleHost";
    version = "7.4.6";
    hash = "sha256-aVN0nNdXRnDUDIIrBTs9KmhDyyuE171WzGwpgIQEtf8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.consolehost/7.4.6/microsoft.powershell.consolehost.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.CoreCLR.Eventing";
    version = "7.4.6";
    hash = "sha256-2B1Yx/vbV6O+xmeLT1UP9jXnEpLZLhzyqEt10dwADl4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.coreclr.eventing/7.4.6/microsoft.powershell.coreclr.eventing.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.MarkdownRender";
    version = "7.2.1";
    hash = "sha256-SiijU75UwtzyJfQhgyxOG4Y0pAIfitPYIZ3EQrtdZXo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.markdownrender/7.2.1/microsoft.powershell.markdownrender.7.2.1.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.Native";
    version = "7.4.0";
    hash = "sha256-XOkDRXtqwKhWXhORbZu8/9SdMfwC3Rn7uGjxfl5i4kk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.native/7.4.0/microsoft.powershell.native.7.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.SDK";
    version = "7.4.6";
    hash = "sha256-M1f1m3Zuk+xIrQLPvlhg3aTgxISfgzzNN0IGFFHtd7g=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.sdk/7.4.6/microsoft.powershell.sdk.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.PowerShell.Security";
    version = "7.4.6";
    hash = "sha256-itrXzf6Le8N4aw6LC2YvqiD2pABqhMhv1TCqoDvXDN4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.powershell.security/7.4.6/microsoft.powershell.security.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Security.Extensions";
    version = "1.2.0";
    hash = "sha256-Ke2pH+rN3kvndKAeBrLWaBICHgm5Y5NqWXyf4NBIC8c=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.security.extensions/1.2.0/microsoft.security.extensions.1.2.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.10.0";
    hash = "sha256-3YjVGK2zEObksBGYg8b/CqoJgLQ1jUv4GCWNjDhLRh4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.testplatform.objectmodel/17.10.0/microsoft.testplatform.objectmodel.17.10.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.10.0";
    hash = "sha256-+yzP3FY6WoOosSpYnB7duZLhOPUZMQYy8zJ1d3Q4hK4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.testplatform.testhost/17.10.0/microsoft.testplatform.testhost.17.10.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading";
    version = "17.6.40";
    hash = "sha256-5HtsgSPV5RdaPREGDvJ7qMOFubb1wMyHwkfTnZs9Zsc=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.visualstudio.threading/17.6.40/microsoft.visualstudio.threading.17.6.40.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "17.6.40";
    hash = "sha256-WghLNITEsKTV5pCjogmhfsVD3iO7ghTk0KNrOXzKSS0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.visualstudio.threading.analyzers/17.6.40/microsoft.visualstudio.threading.analyzers.17.6.40.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Validation";
    version = "17.6.11";
    hash = "sha256-Lkjp9Ove4+CFP06x/toYpJEiAinuTfn/o+oh0fW3pGM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.visualstudio.validation/17.6.11/microsoft.visualstudio.validation.17.6.11.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "4.7.0";
    hash = "sha256-+jWCwRqU/J/jLdQKDFm93WfIDrDMXMJ984UevaQMoi8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.win32.registry/4.7.0/microsoft.win32.registry.4.7.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    hash = "sha256-9kylPGfKZc58yFqNKa77stomcoNnMeERXozWJzDcUIA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.win32.registry/5.0.0/microsoft.win32.registry.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry.AccessControl";
    version = "8.0.0";
    hash = "sha256-F2/VVsc5c3RpsraXAx63P8OdZA61Hh1HbirYI3U1FT4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.win32.registry.accesscontrol/8.0.0/microsoft.win32.registry.accesscontrol.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "8.0.0";
    hash = "sha256-UcxurEamYD+Bua0PbPNMYAZaRulMrov8CfbJGIgTaRQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.win32.systemevents/8.0.0/microsoft.win32.systemevents.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "9.0.0-preview.6.24327.7";
    hash = "sha256-EMYSgw0+VHD5lFbfCy597cRy99yXKEJkzhHxGzQL5yI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.win32.systemevents/9.0.0-preview.6.24327.7/microsoft.win32.systemevents.9.0.0-preview.6.24327.7.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.Windows.Compatibility";
    version = "8.0.10";
    hash = "sha256-VlLNyPBhHsg96Oq3Z8/bxK0iaSQqiUsQ+hQo3rGD3FU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.windows.compatibility/8.0.10/microsoft.windows.compatibility.8.0.10.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.WSMan.Management";
    version = "7.4.6";
    hash = "sha256-ZeoySolEC7AaRHJxq2hdaPRRBGj7knb8tGMe0GrACas=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.wsman.management/7.4.6/microsoft.wsman.management.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.WSMan.Runtime";
    version = "7.4.6";
    hash = "sha256-69bvj55KynMJ8gWC8Xn9L/3yX2UuxaBwizDMGUyHO2Q=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/microsoft.wsman.runtime/7.4.6/microsoft.wsman.runtime.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "Nerdbank.Streams";
    version = "2.10.69";
    hash = "sha256-a0hXKhR7dv6Vm4rlUOD2ffBKG49CC3wzXLCHeTz1ms4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/nerdbank.streams/2.10.69/nerdbank.streams.2.10.69.nupkg";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.3";
    hash = "sha256-Prh2RPebz/s8AzHb2sPHg3Jl8s31inv9k+Qxd293ybo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/netstandard.library/2.0.3/netstandard.library.2.0.3.nupkg";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/newtonsoft.json/13.0.1/newtonsoft.json.13.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/newtonsoft.json/13.0.3/newtonsoft.json.13.0.3.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.DebugAdapter";
    version = "0.19.9";
    hash = "sha256-lDhi1QrTN3EdsccjAJLq+/zb1xriLbJ2yVqXA6Pw0VQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.debugadapter/0.19.9/omnisharp.extensions.debugadapter.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.DebugAdapter.Client";
    version = "0.19.9";
    hash = "sha256-7Ro5EJUU94weWTgkrIBSZgFXETCvaHAhqFdGCQ1pjOo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.debugadapter.client/0.19.9/omnisharp.extensions.debugadapter.client.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.DebugAdapter.Server";
    version = "0.19.9";
    hash = "sha256-AdXTmHV0Gp1VM/xsnmpW/vGd8zKe5YqZTPxHQZ4e3s4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.debugadapter.server/0.19.9/omnisharp.extensions.debugadapter.server.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.DebugAdapter.Shared";
    version = "0.19.9";
    hash = "sha256-fFXgZLUml0cWYwkWKTvsu4JGYKlE1l3GsjT85/JVxEc=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.debugadapter.shared/0.19.9/omnisharp.extensions.debugadapter.shared.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.JsonRpc";
    version = "0.19.9";
    hash = "sha256-n/DjyqXDVxWIPZZ/kdNak7gTFD6638bJtvW3hrEZFWU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.jsonrpc/0.19.9/omnisharp.extensions.jsonrpc.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.JsonRpc.Generators";
    version = "0.19.9";
    hash = "sha256-38+lTizxqeBkWp6ZvMOe2dVsCG1PbQXjXgerXAsK+zw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.jsonrpc.generators/0.19.9/omnisharp.extensions.jsonrpc.generators.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.LanguageClient";
    version = "0.19.9";
    hash = "sha256-jGyZKoRRrWsROVi0/uNbroSdeZZ1I5ZxXAIT4d4SpIo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.languageclient/0.19.9/omnisharp.extensions.languageclient.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.LanguageProtocol";
    version = "0.19.9";
    hash = "sha256-L1O76h4n+qYDCvnKS3j3rwHDW60S4b7s8Cgg8sBbogw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.languageprotocol/0.19.9/omnisharp.extensions.languageprotocol.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.LanguageServer";
    version = "0.19.9";
    hash = "sha256-cGIRuIqUl3pKfYpeT2mY4RigbZOa2yGf1itbSFydZW0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.languageserver/0.19.9/omnisharp.extensions.languageserver.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "OmniSharp.Extensions.LanguageServer.Shared";
    version = "0.19.9";
    hash = "sha256-S27e9BjRaaVcbUle+MF0nRxjHS/fIhNqDyr3aBZyiog=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/omnisharp.extensions.languageserver.shared/0.19.9/omnisharp.extensions.languageserver.shared.0.19.9.nupkg";
  })
  (fetchNuGet {
    pname = "PowerShellStandard.Library";
    version = "5.1.1";
    hash = "sha256-WkUZREiYoMpAVgj5jmbDbkohdnZSjHfw9iLfKyApqCo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/powershellstandard.library/5.1.1/powershellstandard.library.5.1.1.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.globalization/4.3.0/runtime.any.system.globalization.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.io/4.3.0/runtime.any.system.io.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.reflection/4.3.0/runtime.any.system.reflection.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.reflection.extensions/4.3.0/runtime.any.system.reflection.extensions.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.reflection.primitives/4.3.0/runtime.any.system.reflection.primitives.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.resources.resourcemanager/4.3.0/runtime.any.system.resources.resourcemanager.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.runtime/4.3.0/runtime.any.system.runtime.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.runtime.handles/4.3.0/runtime.any.system.runtime.handles.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.runtime.interopservices/4.3.0/runtime.any.system.runtime.interopservices.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.text.encoding/4.3.0/runtime.any.system.text.encoding.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.any.system.threading.tasks/4.3.0/runtime.any.system.threading.tasks.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.linux-arm.runtime.native.System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-m5+od7ZhlzImwSE9E7Qq1nH3A3muXwCnsvrVUoJ7+WE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.linux-arm.runtime.native.system.io.ports/8.0.0/runtime.linux-arm.runtime.native.system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.linux-arm64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-IgbG3HT3A0VItWl5asE7Hk0zaQjQneKQS9f65cQAjLI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.linux-arm64.runtime.native.system.io.ports/8.0.0/runtime.linux-arm64.runtime.native.system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-44oujSHhc0Nl2WCvLYkScrAyqNAlbGfOnlzPwCofwlA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.linux-x64.runtime.native.system.io.ports/8.0.0/runtime.linux-x64.runtime.native.system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.native.system/4.3.0/runtime.native.system.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Data.SqlClient.sni";
    version = "4.7.0";
    hash = "sha256-cj0+BpmoibwOWj2wNXwONJeTGosmFwhD349zPjNaBK0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.native.system.data.sqlclient.sni/4.7.0/runtime.native.system.data.sqlclient.sni.4.7.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-BqExVU/zHj7o++mzOpY9y+i9yZZVbcGmO/D4mRzigY8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.native.system.io.ports/8.0.0/runtime.native.system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.osx-arm64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-oFMF60yyTy3fXwLlXJkNUtzdRz4EyxevAUIcfcVESCE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.osx-arm64.runtime.native.system.io.ports/8.0.0/runtime.osx-arm64.runtime.native.system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.osx-x64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-b2J9DcunMtChpuyNC0XN39Z01Wr738HI/syJW1n9bfE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.osx-x64.runtime.native.system.io.ports/8.0.0/runtime.osx-x64.runtime.native.system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.unix.system.private.uri/4.3.0/runtime.unix.system.private.uri.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.win-arm64.runtime.native.System.Data.SqlClient.sni";
    version = "4.4.0";
    hash = "sha256-8xGiqk5g4kM79//SirozmDtDpqwVXH3CmvIs7GNwfh0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.win-arm64.runtime.native.system.data.sqlclient.sni/4.4.0/runtime.win-arm64.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.win-x64.runtime.native.System.Data.SqlClient.sni";
    version = "4.4.0";
    hash = "sha256-HoXKGBkue0RJT1SZxAliVmT5rbfU3xD8mH8hfCvRxwQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.win-x64.runtime.native.system.data.sqlclient.sni/4.4.0/runtime.win-x64.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "runtime.win-x86.runtime.native.System.Data.SqlClient.sni";
    version = "4.4.0";
    hash = "sha256-jPnWzDcbufO51GLGjynWHy0b+5PBqNxM+VKmSrObeUw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/runtime.win-x86.runtime.native.system.data.sqlclient.sni/4.4.0/runtime.win-x86.runtime.native.system.data.sqlclient.sni.4.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.buffers/4.5.1/system.buffers.4.5.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "8.0.0";
    hash = "sha256-uwVhi3xcvX7eiOGQi7dRETk3Qx1EfHsUfchZsEto338=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.codedom/8.0.0/system.codedom.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.5.0";
    hash = "sha256-BliqYlL9ntbMXo5d7NUrKXwYN+PqdyqDIS5bp4qVr7Q=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.collections.immutable/1.5.0/system.collections.immutable.1.5.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "5.0.0";
    hash = "sha256-GdwSIjLMM0uVfE56VUSLVNgpW0B//oCeSFj8/hSlbM8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.collections.immutable/5.0.0/system.collections.immutable.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "8.0.0";
    hash = "sha256-F7OVjKNwpqbUh8lTidbqJWYi476nsq9n+6k0+QVRo3w=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.collections.immutable/8.0.0/system.collections.immutable.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "5.0.0";
    hash = "sha256-0pST1UHgpeE6xJrYf5R+U7AwIlH3rVC3SpguilI/MAg=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.componentmodel.annotations/5.0.0/system.componentmodel.annotations.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Composition";
    version = "8.0.0";
    hash = "sha256-MnKdjE/qIvAmEeRc3gOn5uJhT0TI3UnUJPjj3TLHFQo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.componentmodel.composition/8.0.0/system.componentmodel.composition.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Composition.Registration";
    version = "8.0.0";
    hash = "sha256-m0DmAA1V3/sbvy0YFrQeODAXGGPMmBExHYlAyZlE6j8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.componentmodel.composition.registration/8.0.0/system.componentmodel.composition.registration.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "8.0.1";
    hash = "sha256-2vgU/BBFDOO2506UX6mtuBQ9c2bCShLLhoy67l7418E=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.configuration.configurationmanager/8.0.1/system.configuration.configurationmanager.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Data.Odbc";
    version = "8.0.1";
    hash = "sha256-LmqokSy9D1SDDFiezsOKyhT47vHwAbRqVX68Alp/uwk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.data.odbc/8.0.1/system.data.odbc.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Data.OleDb";
    version = "8.0.1";
    hash = "sha256-umcrU6CFFItewo5y2JYsBFM5lu45r0f9Jkh/3g9xtto=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.data.oledb/8.0.1/system.data.oledb.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Data.SqlClient";
    version = "4.8.6";
    hash = "sha256-Qc/yco3e0+6jP8UiMA0ERlfSEKdINv0BmHixh9Z8fJQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.data.sqlclient/4.8.6/system.data.sqlclient.4.8.6.nupkg";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "6.0.0";
    hash = "sha256-RY9uWSPdK2fgSwlj1OHBGBVo3ZvGQgBJNzAsS5OGMWc=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.diagnostics.diagnosticsource/6.0.0/system.diagnostics.diagnosticsource.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.1";
    hash = "sha256-zmwHjcJgKcbkkwepH038QhcnsWMJcHys+PEbFGC0Jgo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.diagnostics.diagnosticsource/8.0.1/system.diagnostics.diagnosticsource.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "9.0.0";
    hash = "sha256-1VzO9i8Uq2KlTw1wnCCrEdABPZuB2JBD5gBsMTFTSvE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.diagnostics.diagnosticsource/9.0.0/system.diagnostics.diagnosticsource.9.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "8.0.1";
    hash = "sha256-zvqd72pwgcGoa1nH3ZT1C0mP9k53vFLJ69r5MCQ1saA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.diagnostics.eventlog/8.0.1/system.diagnostics.eventlog.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.PerformanceCounter";
    version = "8.0.1";
    hash = "sha256-B+rMR/+8rOA9/5PV77d8LUQyZdlL04+H2zLJMBHic4Q=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.diagnostics.performancecounter/8.0.1/system.diagnostics.performancecounter.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.DirectoryServices";
    version = "8.0.0";
    hash = "sha256-a6ECGvsDqHPZuaG920zMjcCOBD2Kvg8jWpSacgL4a7A=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.directoryservices/8.0.0/system.directoryservices.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.DirectoryServices.AccountManagement";
    version = "8.0.1";
    hash = "sha256-dtsdt9e1VJZbTshj7AC2k3gQ+0qGmv5haRhHkCjHm6M=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.directoryservices.accountmanagement/8.0.1/system.directoryservices.accountmanagement.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.DirectoryServices.Protocols";
    version = "8.0.0";
    hash = "sha256-Hq3/Y2QpZlJUY52W6WYpiUSQsiMWlxvevLBF+icpGzo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.directoryservices.protocols/8.0.0/system.directoryservices.protocols.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "8.0.10";
    hash = "sha256-GOmBRym8DI9J3t2apGV0fTdpTgFL3hCJtzeUvgDDGD4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.drawing.common/8.0.10/system.drawing.common.8.0.10.nupkg";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "9.0.0-preview.6.24327.6";
    hash = "sha256-V9W88CrA8IlM9Hn6/iW+6nzzgsTnU1uqCMzdu7crZ4c=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.drawing.common/9.0.0-preview.6.24327.6/system.drawing.common.9.0.0-preview.6.24327.6.nupkg";
  })
  (fetchNuGet {
    pname = "System.Formats.Asn1";
    version = "6.0.0";
    hash = "sha256-KaMHgIRBF7Nf3VwOo+gJS1DcD+41cJDPWFh+TDQ8ee8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.formats.asn1/6.0.0/system.formats.asn1.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Formats.Asn1";
    version = "8.0.1";
    hash = "sha256-may/Wg+esmm1N14kQTG4ESMBi+GQKPp0ZrrBo/o6OXM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.formats.asn1/8.0.1/system.formats.asn1.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.globalization/4.3.0/system.globalization.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.io/4.3.0/system.io.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.IO.Packaging";
    version = "8.0.1";
    hash = "sha256-xf0BAfqQvITompBsvfpxiLts/6sRQEzdjNA3f/q/vY4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.io.packaging/8.0.1/system.io.packaging.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "7.0.0";
    hash = "sha256-W2181khfJUTxLqhuAVRhCa52xZ3+ePGOLIPwEN8WisY=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.io.pipelines/7.0.0/system.io.pipelines.7.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.IO.Pipes.AccessControl";
    version = "5.0.0";
    hash = "sha256-3yFWwBEvLy8bQt4h6R9QoQr/QOTCthnijnEhz0pahUo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.io.pipes.accesscontrol/5.0.0/system.io.pipes.accesscontrol.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.IO.Ports";
    version = "8.0.0";
    hash = "sha256-G8j9c0erBzZfJAVlW08XoE58gPhiNWJE78sFaBV2e4Q=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.io.ports/8.0.0/system.io.ports.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "8.0.0";
    hash = "sha256-HwpfDb++q7/vxR6q57mGFgl5U0vxy+oRJ6orFKORfP0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.management/8.0.0/system.management.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Management.Automation";
    version = "7.4.6";
    hash = "sha256-o66CJx0Mq3dYUGyJrsAijz3AhxLObxfFe3hdbU8fd+M=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.management.automation/7.4.6/system.management.automation.7.4.6.nupkg";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.4";
    hash = "sha256-3sCEfzO4gj5CYGctl9ZXQRRhwAraMQfse7yzKoRe65E=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.memory/4.5.4/system.memory.4.5.4.nupkg";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.memory/4.5.5/system.memory.4.5.5.nupkg";
  })
  (fetchNuGet {
    pname = "System.Net.Http.WinHttpHandler";
    version = "8.0.2";
    hash = "sha256-BpF4fKNLIU7JVjJskCgArdJBP3pFj3YDepEIdZvZYE4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.net.http.winhttphandler/8.0.2/system.net.http.winhttphandler.8.0.2.nupkg";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.4.0";
    hash = "sha256-auXQK2flL/JpnB/rEcAcUm4vYMCYMEMiWOCAlIaqu2U=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.numerics.vectors/4.4.0/system.numerics.vectors.4.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    hash = "sha256-qdSTIFgf2htPS+YhLGjAGiLN8igCYJnCCo6r78+Q+c8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.numerics.vectors/4.5.0/system.numerics.vectors.4.5.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Private.ServiceModel";
    version = "4.10.3";
    hash = "sha256-F4ZQfB7i7K5jYeV2ZGWzi3GtnTQG+7ucITof06TIQ3w=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.private.servicemodel/4.10.3/system.private.servicemodel.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.private.uri/4.3.0/system.private.uri.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.0";
    hash = "sha256-hXB18OsiUHSCmRF3unAfdUEcbXVbG6/nZxcyz13oe9Y=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reactive/6.0.0/system.reactive.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection/4.3.0/system.reflection.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection.Context";
    version = "8.0.0";
    hash = "sha256-4ArfguTY4FmbNccexnqwMpmTkDHlA5sCczQ5Ri5kA94=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection.context/8.0.0/system.reflection.context.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection.DispatchProxy";
    version = "4.7.1";
    hash = "sha256-Oi+l32p73ZxwcB6GrSS2m25BccfpuwbY4eyFEwUe0IM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection.dispatchproxy/4.7.1/system.reflection.dispatchproxy.4.7.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection.extensions/4.3.0/system.reflection.extensions.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    hash = "sha256-JJfgaPav7UfEh4yRAQdGhLZF1brr0tUWPl6qmfNWq/E=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection.metadata/1.6.0/system.reflection.metadata.1.6.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "8.0.0";
    hash = "sha256-dQGC30JauIDWNWXMrSNOJncVa1umR1sijazYwUDdSIE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection.metadata/8.0.0/system.reflection.metadata.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.reflection.primitives/4.3.0/system.reflection.primitives.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.resources.resourcemanager/4.3.0/system.resources.resourcemanager.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime/4.3.0/system.runtime.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime.Caching";
    version = "8.0.1";
    hash = "sha256-Uj9k5meIDXlEm8V5MWyzaWz4YA+8OWHE5K8kMq0kTR4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime.caching/8.0.1/system.runtime.caching.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.3";
    hash = "sha256-lnZMUqRO4RYRUeSO8HSJ9yBHqFHLVbmenwHWkIU20ak=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime.compilerservices.unsafe/4.5.3/system.runtime.compilerservices.unsafe.4.5.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime.compilerservices.unsafe/6.0.0/system.runtime.compilerservices.unsafe.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime.handles/4.3.0/system.runtime.handles.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime.interopservices/4.3.0/system.runtime.interopservices.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.3.0";
    hash = "sha256-MYpl6/ZyC6hjmzWRIe+iDoldOMW1mfbwXsduAnXIKGA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.runtime.interopservices.runtimeinformation/4.3.0/system.runtime.interopservices.runtimeinformation.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "4.7.0";
    hash = "sha256-/9ZCPIHLdhzq7OW4UKqTsR0O93jjHd6BRG1SRwgHE1g=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.accesscontrol/4.7.0/system.security.accesscontrol.4.7.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    hash = "sha256-ueSG+Yn82evxyGBnE49N4D+ngODDXgornlBtQ3Omw54=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.accesscontrol/5.0.0/system.security.accesscontrol.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "6.0.0";
    hash = "sha256-qOyWEBbNr3EjyS+etFG8/zMbuPjA+O+di717JP9Cxyg=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.accesscontrol/6.0.0/system.security.accesscontrol.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "6.0.1";
    hash = "sha256-Ri4m95ZBfopDUGVahbvUIzuUy9D3FQwcXprP2I6IUUE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.accesscontrol/6.0.1/system.security.accesscontrol.6.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "6.0.1";
    hash = "sha256-OJ4NJ8E/8l86aR+Hsw+k/7II63Y/zPS+MgC+UfeCXHM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.cryptography.pkcs/6.0.1/system.security.cryptography.pkcs.6.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "8.0.1";
    hash = "sha256-KMNIkJ3yQ/5O6WIhPjyAIarsvIMhkp26A6aby5KkneU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.cryptography.pkcs/8.0.1/system.security.cryptography.pkcs.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "8.0.0";
    hash = "sha256-fb0pa9sQxN+mr0vnXg1Igbx49CaOqS+GDkTfWNboUvs=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.cryptography.protecteddata/8.0.0/system.security.cryptography.protecteddata.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Xml";
    version = "6.0.1";
    hash = "sha256-spXV8cWZu0V3liek1936REtdpvS4fQwc98JvacO1oJU=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.cryptography.xml/6.0.1/system.security.cryptography.xml.6.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Xml";
    version = "8.0.2";
    hash = "sha256-9TCmVyMB4+By/ipU8vdYDtSnw1tkkebnXXVRdT78+28=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.cryptography.xml/8.0.2/system.security.cryptography.xml.8.0.2.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Permissions";
    version = "8.0.0";
    hash = "sha256-+YUPY+3HnTmfPLZzr+5qEk0RqalCbFZBgLXee1yCH1M=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.permissions/8.0.0/system.security.permissions.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.3.0";
    hash = "sha256-rjudVUHdo8pNJg2EVEn0XxxwNo5h2EaYo+QboPkXlYk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.principal/4.3.0/system.security.principal.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.7.0";
    hash = "sha256-rWBM2U8Kq3rEdaa1MPZSYOOkbtMGgWyB8iPrpIqmpqg=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.principal.windows/4.7.0/system.security.principal.windows.4.7.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    hash = "sha256-CBOQwl9veFkrKK2oU8JFFEiKIh/p+aJO+q9Tc2Q/89Y=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.security.principal.windows/5.0.0/system.security.principal.windows.5.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.Duplex";
    version = "4.10.3";
    hash = "sha256-aIhJf9U5ZeObTT2yCUwyVxJmk3f/hkrHhNMG7zL9hnI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.servicemodel.duplex/4.10.3/system.servicemodel.duplex.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.Http";
    version = "4.10.3";
    hash = "sha256-dISjwUtSRu/TLiT6WMVgF3pmgMikIENw3xTn8IJln8U=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.servicemodel.http/4.10.3/system.servicemodel.http.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.NetTcp";
    version = "4.10.3";
    hash = "sha256-DIO8LkIHukgCFeSIgDxPav/IQu9IdMtyweAxVI9agFM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.servicemodel.nettcp/4.10.3/system.servicemodel.nettcp.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.Primitives";
    version = "4.10.3";
    hash = "sha256-NiCgBnMuq2M+TPaS0rxyuaZJXo7Ytka8HeYZ3xq61rI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.servicemodel.primitives/4.10.3/system.servicemodel.primitives.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.Security";
    version = "4.10.3";
    hash = "sha256-L1FanczQ680AYHe3nYnoikwc/3S0cLZhvcBERU8afXk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.servicemodel.security/4.10.3/system.servicemodel.security.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceModel.Syndication";
    version = "8.0.0";
    hash = "sha256-vKgiDGQBcaEQiWpfU6kGRtlJslBQXtFGqF+EVk/u7kI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.servicemodel.syndication/8.0.0/system.servicemodel.syndication.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.ServiceProcess.ServiceController";
    version = "8.0.1";
    hash = "sha256-2cXTzNOyXqJinFPzdVJ9Gu6qrFtycfivu7RHDzBJic8=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.serviceprocess.servicecontroller/8.0.1/system.serviceprocess.servicecontroller.8.0.1.nupkg";
  })
  (fetchNuGet {
    pname = "System.Speech";
    version = "8.0.0";
    hash = "sha256-ogtnRBUcTruWZ0NVivKUupkVPAINigOBuJ0Gv/T1wQk=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.speech/8.0.0/system.speech.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.text.encoding/4.3.0/system.text.encoding.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "8.0.0";
    hash = "sha256-fjCLQc1PRW0Ix5IZldg0XKv+J1DqPSfu9pjMyNBp7dE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.text.encoding.codepages/8.0.0/system.text.encoding.codepages.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    hash = "sha256-IUQkQkV9po1LC0QsqrilqwNzPvnc+4eVvq+hCvq8fvE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.text.encodings.web/8.0.0/system.text.encodings.web.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.threading/4.3.0/system.threading.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Threading.AccessControl";
    version = "8.0.0";
    hash = "sha256-8ugqZSyqfTfIBt4xcLdvb6BmBTHWFsGATkasNvsEtJQ=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.threading.accesscontrol/8.0.0/system.threading.accesscontrol.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Threading.AccessControl";
    version = "9.0.0-preview.6.24327.7";
    hash = "sha256-m29mfO1xFnDagIZsh9Ye6IlFRROMPnT+WKSMpkKiemo=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.threading.accesscontrol/9.0.0-preview.6.24327.7/system.threading.accesscontrol.9.0.0-preview.6.24327.7.nupkg";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "6.0.0";
    hash = "sha256-klGYnsyrjvXaGeqgfnMf/dTAMNtcHY+zM4Xh6v2JfuE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.threading.channels/6.0.0/system.threading.channels.6.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.threading.tasks/4.3.0/system.threading.tasks.4.3.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.threading.tasks.extensions/4.5.4/system.threading.tasks.extensions.4.5.4.nupkg";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    hash = "sha256-niH6l2fU52vAzuBlwdQMw0OEoRS/7E1w5smBFoqSaAI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.valuetuple/4.5.0/system.valuetuple.4.5.0.nupkg";
  })
  (fetchNuGet {
    pname = "System.Web.Services.Description";
    version = "4.10.3";
    hash = "sha256-iqk/Q6jZ/DZYHrsuE8X3NqZiCyvuTMxh2870A0LkmeM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.web.services.description/4.10.3/system.web.services.description.4.10.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.Windows.Extensions";
    version = "8.0.0";
    hash = "sha256-aHkz7LtmUDDRS7swQM0i6dDVUytRCMYeA2CfaeVA2Y0=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/system.windows.extensions/8.0.0/system.windows.extensions.8.0.0.nupkg";
  })
  (fetchNuGet {
    pname = "Validation";
    version = "2.4.18";
    hash = "sha256-ByITVSjsqVglWPIRaZ3i1P3bHh8+OB6BWgDA8f8qTFI=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/validation/2.4.18/validation.2.4.18.nupkg";
  })
  (fetchNuGet {
    pname = "xunit";
    version = "2.9.0";
    hash = "sha256-OszmJA1wZvIsvTe3uIFPNaDMVXEccbCH/BXrbIpvP9M=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit/2.9.0/xunit.2.9.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.abstractions";
    version = "2.0.2";
    hash = "sha256-w5APCW7suBdoDOmQqm/8Gq6+Sk88JcTR09zjmj9s17E=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.abstractions/2.0.2/xunit.abstractions.2.0.2.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.abstractions";
    version = "2.0.3";
    hash = "sha256-0D1y/C34iARI96gb3bAOG8tcGPMjx+fMabTPpydGlAM=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.abstractions/2.0.3/xunit.abstractions.2.0.3.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.analyzers";
    version = "1.15.0";
    hash = "sha256-Eoe1OE/dq6KOH9s2zfrsmo3PbRuIAyyyZoXjDwuSvfA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.analyzers/1.15.0/xunit.analyzers.1.15.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.assert";
    version = "2.9.0";
    hash = "sha256-3GUZ0loDa/3WDXRuBQdghsKXE/bZrCBJ5Bopr43SuVA=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.assert/2.9.0/xunit.assert.2.9.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.core";
    version = "2.9.0";
    hash = "sha256-c2Dze5Nr/tP5nsS/jVlU3eR0uSBf+zX7Vv0yNZ/UY3o=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.core/2.9.0/xunit.core.2.9.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.core";
    version = "2.4.0";
    hash = "sha256-LbuXEcEJjGn3L6FCbC119+MY/QLvfLlGkCeAsCsZqGE=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.extensibility.core/2.4.0/xunit.extensibility.core.2.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.core";
    version = "2.9.0";
    hash = "sha256-dYulj4Y+kEs2dpjGvKPuIhk3gszlVo+yN1XSfjrjPxw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.extensibility.core/2.9.0/xunit.extensibility.core.2.9.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.execution";
    version = "2.4.0";
    hash = "sha256-chRJEazwq93yhVONlbtTI1znqYy0gdAoQajPRnhM/i4=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.extensibility.execution/2.4.0/xunit.extensibility.execution.2.4.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.execution";
    version = "2.9.0";
    hash = "sha256-1wRMsC+ZGdP4U/turB4mRfO0yh6uN47Vn1DJHyN/N3s=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.extensibility.execution/2.9.0/xunit.extensibility.execution.2.9.0.nupkg";
  })
  (fetchNuGet {
    pname = "xunit.runner.visualstudio";
    version = "2.8.2";
    hash = "sha256-UlfK348r8kJuraywfdCtpJJxHkv04wPNzpUaz4UM/60=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.runner.visualstudio/2.8.2/xunit.runner.visualstudio.2.8.2.nupkg";
  })
  (fetchNuGet {
    pname = "Xunit.SkippableFact";
    version = "1.4.13";
    hash = "sha256-pLtx0/2oTKYO1Y1Vg3k/Eli2OWHT5uorGdBp2uXvFfw=";
    url = "https://pkgs.dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_packaging/e59e749b-417c-4664-9322-c190bb60de7f/nuget/v3/flat2/xunit.skippablefact/1.4.13/xunit.skippablefact.1.4.13.nupkg";
  })
]
